# Generated by Django 4.1.3 on 2023-01-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryitemlist',
            fields=[
                ('categoryid', models.OneToOneField(db_column='CategoryID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.categorylist')),
            ],
            options={
                'db_table': 'CategoryItemList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemlist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('itemname', models.CharField(blank=True, db_column='ItemName', max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
            ],
            options={
                'db_table': 'ItemList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('orderid', models.OneToOneField(db_column='OrderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.foodorder')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('netvalue', models.IntegerField(db_column='NetValue')),
            ],
            options={
                'db_table': 'OrderItem',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='foodorderitems',
            name='foodorderid',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Foodorderitems',
        ),
    ]
